colors:
  primary:
    background: '#1c1c1c'
    foreground: '#c5c8c6'
  cursor:
    text: '#1d1f21'
    cursor: '#c5c8c6'
  normal:
    black:   '#333333'
    red:     '#cc6666'
    green:   '#81bd68'
    yellow:  '#f0c674'
    blue:    '#6699ff'
    magenta: '#b294bb'
    cyan:    '#789bba'
    white:   '#c5c8c6'
  bright:
    black:   '#595959'
    red:     '#d98c8c'
    green:   '#a7d095'
    yellow:  '#f5daa3'
    blue:    '#9ab4cb'
    magenta: '#c7b1cd'
    cyan:    '#add2cd'
    white:   '#e5e6e5'
  dim:
    black:   '#969896'
    red:     '#cc6666'
    green:   '#81bd68'
    yellow:  '#f0c674'
    blue:    '#81a2be'
    magenta: '#b294bb'
    cyan:    '#8abeb7'
    white:   '#c5c8c6'
