[colors.normal]
black = "#282c34"
blue = "#51afef"
cyan = "#46d9ff"
green = "#98be65"
magenta = "#c678dd"
red = "#ff6c6b"
white = "#bbc2cf"
yellow = "#ecbe7b"

[colors.primary]
background = "#282c34"
foreground = "#bbc2cf"
