colors:
  primary:
    background: '#ffffff'
    foreground: '#373b41'
  normal:
    black:   '#1d1f21'
    red:     '#cc342b'
    green:   '#198844'
    yellow:  '#fba922'
    blue:    '#3971ed'
    magenta: '#a36ac7'
    cyan:    '#3971ed'
    white:   '#c5c8c6'
  bright:
    black:   '#969896'
    red:     '#cc342b'
    green:   '#198844'
    yellow:  '#fba922'
    blue:    '#3971ed'
    magenta: '#a36ac7'
    cyan:    '#3971ed'
    white:   '#ffffff'
  dim:
    black:   '#1d1f21'
    red:     '#cc342b'
    green:   '#198844'
    yellow:  '#fba922'
    blue:    '#3971ed'
    magenta: '#a36ac7'
    cyan:    '#3971ed'
    white:   '#c5c8c6'
