colors:
  primary:
    background: '#f7f7f7'
    foreground: '#000000'
  cursor:
    cursor: '#007acc'
    text: '#bfdbfe'
  selection:
    background: '#bfdbfe'
    text: '#000000'
  normal:
    black: '#000000'
    red: '#aa3731'
    green: '#448c27'
    yellow: '#cb9000'
    blue: '#325cc0'
    magenta: '#7a3e9d'
    cyan: '#0083b2'
    white: '#f7f7f7'
  bright:
    black: '#777777'
    red: '#f05050'
    green: '#60cb00'
    yellow: '#ffbc5d'
    blue: '#007acc'
    magenta: '#e64ce6'
    cyan: '#00aacb'
    white: '#f7f7f7'
  dim:
    black: '#000000'
    red: '#aa3731'
    green: '#448c27'
    yellow: '#cb9000'
    blue: '#325cc0'
    magenta: '#7a3e9d'
    cyan: '#0083b2'
    white: '#f7f7f7'
