colors:
  primary:
    background: '#0f111b'
    foreground: '#ecf0c1'
  cursor:
    text: '#0f111b'
    cursor: '#ecf0c1'
  normal:
    black:   '#000000'
    red:     '#e33400'
    green:   '#5ccc96'
    yellow:  '#b3a1e6'
    blue:    '#00a3cc'
    magenta: '#ce6f8f'
    cyan:    '#7a5ccc'
    white:   '#686f9a'
