#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s "$SCRIPTPATH"/down /tmp/leftwm-theme-down

# Set the theme's configuration file
echo "LoadTheme $SCRIPTPATH/theme.toml" > "$XDG_RUNTIME_DIR"/leftwm/commands.pipe

# Start the compositer
if [ -x "$(command -v picom)" ]; then
  picom -CG --no-fading-openclose &> /dev/null &
fi

# Configure wallpaper
if [ -x "$(command -v feh)" ]; then
  if [ -d "$HOME/.local/share/wallpapers" ]; then
    feh --bg-fill --no-fehbg --randomize "$HOME"/.local/share/wallpapers/* &
  else
    feh --bg-fill --no-fehbg "$SCRIPTPATH"/background.jpg &
  fi
fi

# Launch policy kit
if [ -x "$(command -v lxpolkit)" ]; then
  lxpolkit &
fi

# Launch Simple X Hotkey Daemon
if [ -x "$(command -v sxhkd)" ]; then
  sxhkd &
fi

# Launch Dunst (notification)
if [ -x "$(command -v dunst)" ]; then
  dunst &
fi

# Launch Unclutter (hide mouse cursor)
if [ -x "$(command -v unclutter)" ]; then
  unclutter &
fi

# Launch Flameshot
if [ -x "$(command -v flameshot)" ]; then
  flameshot &
fi

# Display volume icon in systray
if [ -x "$(command -v volumeicon)" ] && [ ! -n "$(pgrep volumeicon)" ]; then
  volumeicon &
fi

# Turn on Numlock
if [ -x "$(command -v numlockx)" ]; then
  numlockx &
fi

# Launch Nextcloud
if [ -x "$(command -v nextcloud)" ]; then
  nextcloud --background &
fi

# Launch Redshift
if [ -x "$(command -v redshift)" ] && [ ! -n "$(pgrep redshift-gtk)" ]; then
  redshift-gtk &
fi

# Launch a session manager
if [ -x "$(command -v lxsession)" ]; then
  lxsession &
fi

# Launch the status bar
killall -q polybar &
sleep 1s
index=0
monitor="$(polybar -m | grep +0+0 | sed s/:.*// | tac)"
leftwm-state -q -n -t "$SCRIPTPATH"/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y
do
  barname="mainbar$index"
  monitor=$monitor offsetx=$x width=$width polybar -c "$SCRIPTPATH"/polybar.config "$barname" &> /dev/null &
  let index=index+1
done

