# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Do not create an empty line at start
add_newline = false

# AWS region and profile
[aws]
format = '[$symbol$profile(\($region\))(\[$duration\])]($style) '

# Battery
[battery]
disabled = true

# Prompt's beginning character customization
[character]
success_symbol = "[❯](bold #6699ff)"
error_symbol = "[❯](bold #cc6666)"
vicmd_symbol = "[❮](bold #789bba)"

# Command duration customization
[cmd_duration]
format = "[took $duration]($style) "
style = "bold #85855e"

# Path customization
[directory]
truncation_length = 10
truncation_symbol = "…/"
truncate_to_repo = true
read_only = " "
read_only_style = "blue"
style = "bold 172"

# Current Git branch
[git_branch]
# symbol = " "
format = "[$symbol$branch]($style) "
style = "bold purple"

# Current Git commit hash
[git_commit]
only_detached = true
format = "[\\[$hash\\]]($style) "
style = "purple"

# Git repo status (ahead, etc...)
[git_status]
disabled = false
style = "bold purple"

# Background jobs customization
[jobs]
threshold = 1

# Prompt on two lines
[line_break]
disabled = false

# Show error code of previous command if failed
[status]
disabled = false

# Prompt's format
format = "$all[\\($status\\)]($style) "
