#!/bin/sh

# Configure wallpaper
if type feh > /dev/null 2>&1; then
	if [ -d "$HOME/.local/share/wallpapers" ]; then
		feh --bg-fill --no-fehbg --randomize "$HOME"/.local/share/wallpapers/* &
	else
		feh --bg-fill --no-fehbg "$HOME"/.config/i3/background.jpg &
	fi
fi

# Launch Simple X Hotkey Daemon
if type sxhkd > /dev/null 2>&1; then
	sxhkd &
fi

# Launch Dunst if installed (notification)
if type dunst > /dev/null 2>&1; then
	dunst &
fi

# Launch Unclutter (hide mouse cursor)
if type unclutter > /dev/null 2>&1; then
	unclutter &
fi

# Launch Flameshot if installed
if type flameshot > /dev/null 2>&1; then
	flameshot &
fi

# Display volume icon in systray
if type volumeicon > /dev/null 2>&1 && [ ! -n "$(pgrep volumeicon)" ]; then
	volumeicon &
fi

# Turn on Numlock
if type numlockx > /dev/null 2>&1; then
	numlockx on &
fi

# Launch a session manager
if type lxpolkit > /dev/null 2>&1; then
	lxpolkit &
fi

# Launch a session manager
if type lxsession > /dev/null 2>&1; then
	lxsession &
fi

# Launch Redshift (night light)
if type redshift > /dev/null 2>&1 && [ ! -n "$(pgrep redshift-gtk)" ]; then
	redshift-gtk &
fi

# Launch Nextcloud client
if type nextcloud > /dev/null 2>&1; then
	nextcloud --background &
fi

# Launch compositer for fancy graphical effects
if type picom > /dev/null 2>&1; then
	picom -CGb --no-fading-openclose &
fi

# GNOME-Keyring for password caching
if type gnome-keyring > /dev/null 2>&1; then
	eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
	export SSH_AUTH_SOCK
fi
