#!/usr/bin/env sh
#=========================================================================
# Author: Gaetan (gaetan@ictpourtous.com) - Twitter: @GaetanICT
# Creation: Sun 22 Aug 2021 12:19:35
# Last modified: Sun 22 Aug 2021 12:19:54
# Version: 1.0
#
# Description: script executed by Xinit when the GUI is Openbox
#=========================================================================

# Launch Simple X Hotkey Daemon
if type sxhkd > /dev/null 2>&1; then
	sxhkd &
fi
# GNOME-Keyring for password caching
if type gnome-keyring > /dev/null 2>&1; then
	eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
	export SSH_AUTH_SOCK
fi
