#!/usr/bin/env sh
#=========================================================================
# Author: Gaetan (gaetan@ictpourtous.com) - Twitter: @astsu777
# Creation: Sun 22 Aug 2021 12:19:35
# Last modified: Mon 23 Aug 2021 16:06:18
# Version: 1.0
#
# Description: script executed by Xinit when the GUI is Openbox
#=========================================================================

# Launch Simple X Hotkey Daemon
if type sxhkd > /dev/null 2>&1; then
	sxhkd &
fi
