#!/usr/bin/env sh
#=========================================================================
# Author: Gaetan (gaetan@ictpourtous.com) - Twitter: @GaetanICT
# Creation: Sun 22 Aug 2021 12:20:13
# Last modified: Sun 29 Aug 2021 11:49:55
# Version: 1.0
#
# Description: script executed by Xinit when 'startx' is run
#=========================================================================

# Default X11 scripts
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 	for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  		[ -x "$f" ] && . "$f"
 	done
 	unset f
fi

# Define what WM/DE to execute
export SESSION="dwm"

# Executed by startx (run your window manager from here)
# If the main GUI has an issue and won't start, use 'jwm' as a failsafe
get_session(){
	case "$SESSION" in
		bspwm) exec bspwm ;;
		dwm) exec dwm ;;
		i3) exec i3 ;;
		jwm) exec jwm ;;
		openbox) exec openbox-session ;;
		xfce) exec startxfce4 ;;
	esac
}

# Common
# Set screen layout if exist
if [ -f "$HOME"/.config/screenlayout/layout.sh ]; then
	. "$HOME"/.config/screenlayout/layout.sh &
fi

# Enable tap-to-click if exist
if [ -f "$HOME"/.config/touchpad.sh ]; then
	/bin/bash "$HOME"/.config/touchpad.sh &
fi

# Set keyboard layout to US-Intl w/ dead keys
if type setxkbmap > /dev/null 2>&1; then
	setxkbmap -layout us -variant intl > /dev/null 2>&1
fi

# Configure keyboard repeat rate
if type xset > /dev/null 2>&1; then
	xset r rate 200 70 > /dev/null 2>&1
fi

# Manage light multimedia keys
if type xfce4-power-manager > /dev/null 2>&1; then
	xfce4-power-manager --daemon &
fi

# Launch clipboard manager
if type clipmenud > /dev/null 2>&1; then
	clipmenud &
fi

# Load .Xresources
if [ -f ~/.config/X11/Xresources ]; then
	xrdb -merge -I$HOME ~/.config/X11/Xresources
else
	xrdb -merge -I$HOME ~/.Xresources
fi

# Lock screen
if type slock > /dev/null 2>&1; then
	# Lock screen after 10 minutes of inactivity
	if type xautolock > /dev/null 2>&1; then
		xautolock -secure -detectsleep -time 10 -locker slock &
	fi
	# Lock screen on suspend/hibernate/lock-session systemd-events
	if type xss-lock > /dev/null 2>&1; then
		xss-lock -- slock &
	fi
fi

# GNOME-Keyring for password/SSH keys caching
if type gnome-keyring > /dev/null 2>&1; then
	eval $(gnome-keyring-daemon --start)
	export SSH_AUTH_SOCK
  	ln -sf "$SSH_AUTH_SOCK" ~/.ssh/ssh_auth_sock
fi

# DWM
if [ "$SESSION" = "dwm" ]; then
	. "$HOME"/.dotfiles/config/X11/x11dwm
fi

# I3
if [ "$SESSION" = "i3" ]; then
	. "$HOME"/.dotfiles/config/X11/x11i3
fi

# Openbox
if [ "$SESSION" = "openbox" ]; then
	. "$HOME"/.dotfiles/config/X11/x11openbox
fi

# XFCE
if [ "$SESSION" = "xfce" ]; then
	. "$HOME"/.dotfiles/config/X11/x11xfce
fi

# Launch the chosen GUI environment (must be last)
get_session "$1"
