#!/bin/sh

# Common
# Source necessary resources for auto-start to work (user's profile not loaded)
export PATH="$HOME/.local/bin:$PATH"
. "$HOME"/.dotfiles/shellconfig/common

# Set screen layout if exist
if [ -f "$HOME"/.config/screenlayout/layout.sh ]; then
	. "$HOME"/.config/screenlayout/layout.sh &
fi

# Enable tap-to-click if exist
if [ -f "$HOME"/.config/touchpad.sh ]; then
	/bin/bash "$HOME"/.config/touchpad.sh &
fi

# Set keyboard layout to US-Intl w/ dead keys
if type setxkbmap > /dev/null 2>&1; then
	setxkbmap -layout us -variant intl > /dev/null 2>&1
fi

# Manage light multimedia keys
if type xfce4-power-manager > /dev/null 2>&1; then
	xfce4-power-manager --daemon &
fi

# Configure keyboard repeat rate
if type xset > /dev/null 2>&1; then
	xset r rate 200 70 > /dev/null 2>&1
fi

# Launch clipboard manager
if type clipmenud > /dev/null 2>&1; then
	clipmenud &
fi

# Lock screen
if type slock > /dev/null 2>&1; then
	# Lock screen after 10 minutes of inactivity
	if type xautolock > /dev/null 2>&1; then
		xautolock -secure -detectsleep -time 10 -locker slock &
	fi
	# Lock screen on suspend/hibernate/lock-session systemd-events
	if type xss-lock > /dev/null 2>&1; then
		xss-lock -- slock &
	fi
fi

# Load .Xresources
if [ -f ~/.config/X11/Xresources ]; then
	xrdb -merge -I$HOME ~/.config/X11/Xresources
else
	xrdb -merge -I$HOME ~/.Xresources
fi

# DWM
if [ "$GDMSESSION" = "dwm" ]; then
	export PATH="$HOME/.local/bin/statusbar:$PATH"
	. "$HOME"/.dotfiles/config/X11/x11dwm
elif [ "$GDMSESSION" = "DWM" ]; then
	export PATH="$HOME/.local/bin/statusbar:$PATH"
	. "$HOME"/.dotfiles/config/X11/x11dwm
fi

# Openbox
if [ "$GDMSESSION" = "openbox" ]; then
	. "$HOME"/.dotfiles/config/X11/x11openbox
elif [ "$GDMSESSION" = "Openbox" ]; then
	. "$HOME"/.dotfiles/config/X11/x11openbox
fi

# XFCE
if [ "$GDMSESSION" = "xfce" ]; then
	. "$HOME"/.dotfiles/config/X11/x11xfce
elif [ "$GDMSESSION" = "Xfce" ]; then
	. "$HOME"/.dotfiles/config/X11/x11xfce
elif [ "$GDMSESSION" = "XFCE" ]; then
	. "$HOME"/.dotfiles/config/X11/x11xfce
fi
